In [2]:
import os
import pandas as pd
import numpy as np
import sqlite3 as sql
import json
from datetime import date

print("libraries imported")

libraries imported

In [11]:
df = pd.read_csv('../usa_spending_old_data/base_awards/psc1550_fy2020.csv',low_memory=False)
print(df.shape)

(490, 286)

In [12]:
df.columns.tolist()

['contract_award_unique_key',
 'award_id_piid',
 'parent_award_agency_id',
 'parent_award_agency_name',
 'parent_award_id_piid',
 'disaster_emergency_fund_codes',
 'outlayed_amount_from_COVID-19_supplementals',
 'obligated_amount_from_COVID-19_supplementals',
 'outlayed_amount_from_IIJA_supplemental',
 'obligated_amount_from_IIJA_supplemental',
 'total_obligated_amount',
 'total_outlayed_amount',
 'current_total_value_of_award',
 'potential_total_value_of_award',
 'award_base_action_date',
 'award_base_action_date_fiscal_year',
 'award_latest_action_date',
 'award_latest_action_date_fiscal_year',
 'period_of_performance_start_date',
 'period_of_performance_current_end_date',
 'period_of_performance_potential_end_date',
 'ordering_period_end_date',
 'solicitation_date',
 'awarding_agency_code',
 'awarding_agency_name',
 'awarding_sub_agency_code',
 'awarding_sub_agency_name',
 'awarding_office_code',
 'awarding_office_name',
 'funding_agency_code',
 'funding_agency_name',
 'funding_sub_agency_code',
 'funding_sub_agency_name',
 'funding_office_code',
 'funding_office_name',
 'treasury_accounts_funding_this_award',
 'federal_accounts_funding_this_award',
 'object_classes_funding_this_award',
 'program_activities_funding_this_award',
 'foreign_funding',
 'foreign_funding_description',
 'sam_exception',
 'sam_exception_description',
 'recipient_uei',
 'recipient_duns',
 'recipient_name',
 'recipient_name_raw',
 'recipient_doing_business_as_name',
 'cage_code',
 'recipient_parent_uei',
 'recipient_parent_duns',
 'recipient_parent_name',
 'recipient_parent_name_raw',
 'recipient_country_code',
 'recipient_country_name',
 'recipient_address_line_1',
 'recipient_address_line_2',
 'recipient_city_name',
 'prime_award_summary_recipient_county_fips_code',
 'recipient_county_name',
 'prime_award_summary_recipient_state_fips_code',
 'recipient_state_code',
 'recipient_state_name',
 'recipient_zip_4_code',
 'prime_award_summary_recipient_cd_original',
 'prime_award_summary_recipient_cd_current',
 'recipient_phone_number',
 'recipient_fax_number',
 'primary_place_of_performance_country_code',
 'primary_place_of_performance_country_name',
 'primary_place_of_performance_city_name',
 'prime_award_summary_place_of_performance_county_fips_code',
 'primary_place_of_performance_county_name',
 'prime_award_summary_place_of_performance_state_fips_code',
 'primary_place_of_performance_state_code',
 'primary_place_of_performance_state_name',
 'primary_place_of_performance_zip_4',
 'prime_award_summary_place_of_performance_cd_original',
 'prime_award_summary_place_of_performance_cd_current',
 'award_or_idv_flag',
 'award_type_code',
 'award_type',
 'idv_type_code',
 'idv_type',
 'multiple_or_single_award_idv_code',
 'multiple_or_single_award_idv',
 'type_of_idc_code',
 'type_of_idc',
 'type_of_contract_pricing_code',
 'type_of_contract_pricing',
 'prime_award_base_transaction_description',
 'solicitation_identifier',
 'number_of_actions',
 'inherently_governmental_functions',
 'inherently_governmental_functions_description',
 'product_or_service_code',
 'product_or_service_code_description',
 'contract_bundling_code',
 'contract_bundling',
 'dod_claimant_program_code',
 'dod_claimant_program_description',
 'naics_code',
 'naics_description',
 'recovered_materials_sustainability_code',
 'recovered_materials_sustainability',
 'domestic_or_foreign_entity_code',
 'domestic_or_foreign_entity',
 'dod_acquisition_program_code',
 'dod_acquisition_program_description',
 'information_technology_commercial_item_category_code',
 'information_technology_commercial_item_category',
 'epa_designated_product_code',
 'epa_designated_product',
 'country_of_product_or_service_origin_code',
 'country_of_product_or_service_origin',
 'place_of_manufacture_code',
 'place_of_manufacture',
 'subcontracting_plan_code',
 'subcontracting_plan',
 'extent_competed_code',
 'extent_competed',
 'solicitation_procedures_code',
 'solicitation_procedures',
 'type_of_set_aside_code',
 'type_of_set_aside',
 'evaluated_preference_code',
 'evaluated_preference',
 'research_code',
 'research',
 'fair_opportunity_limited_sources_code',
 'fair_opportunity_limited_sources',
 'other_than_full_and_open_competition_code',
 'other_than_full_and_open_competition',
 'number_of_offers_received',
 'commercial_item_acquisition_procedures_code',
 'commercial_item_acquisition_procedures',
 'small_business_competitiveness_demonstration_program',
 'simplified_procedures_for_certain_commercial_items_code',
 'simplified_procedures_for_certain_commercial_items',
 'a76_fair_act_action_code',
 'a76_fair_act_action',
 'fed_biz_opps_code',
 'fed_biz_opps',
 'local_area_set_aside_code',
 'local_area_set_aside',
 'price_evaluation_adjustment_preference_percent_difference',
 'clinger_cohen_act_planning_code',
 'clinger_cohen_act_planning',
 'materials_supplies_articles_equipment_code',
 'materials_supplies_articles_equipment',
 'labor_standards_code',
 'labor_standards',
 'construction_wage_rate_requirements_code',
 'construction_wage_rate_requirements',
 'interagency_contracting_authority_code',
 'interagency_contracting_authority',
 'other_statutory_authority',
 'program_acronym',
 'parent_award_type_code',
 'parent_award_type',
 'parent_award_single_or_multiple_code',
 'parent_award_single_or_multiple',
 'major_program',
 'national_interest_action_code',
 'national_interest_action',
 'cost_or_pricing_data_code',
 'cost_or_pricing_data',
 'cost_accounting_standards_clause_code',
 'cost_accounting_standards_clause',
 'government_furnished_property_code',
 'government_furnished_property',
 'sea_transportation_code',
 'sea_transportation',
 'consolidated_contract_code',
 'consolidated_contract',
 'performance_based_service_acquisition_code',
 'performance_based_service_acquisition',
 'multi_year_contract_code',
 'multi_year_contract',
 'contract_financing_code',
 'contract_financing',
 'purchase_card_as_payment_method_code',
 'purchase_card_as_payment_method',
 'contingency_humanitarian_or_peacekeeping_operation_code',
 'contingency_humanitarian_or_peacekeeping_operation',
 'alaskan_native_corporation_owned_firm',
 'american_indian_owned_business',
 'indian_tribe_federally_recognized',
 'native_hawaiian_organization_owned_firm',
 'tribally_owned_firm',
 'veteran_owned_business',
 'service_disabled_veteran_owned_business',
 'woman_owned_business',
 'women_owned_small_business',
 'economically_disadvantaged_women_owned_small_business',
 'joint_venture_women_owned_small_business',
 'joint_venture_economic_disadvantaged_women_owned_small_bus',
 'minority_owned_business',
 'subcontinent_asian_asian_indian_american_owned_business',
 'asian_pacific_american_owned_business',
 'black_american_owned_business',
 'hispanic_american_owned_business',
 'native_american_owned_business',
 'other_minority_owned_business',
 'contracting_officers_determination_of_business_size',
 'contracting_officers_determination_of_business_size_code',
 'emerging_small_business',
 'community_developed_corporation_owned_firm',
 'labor_surplus_area_firm',
 'us_federal_government',
 'federally_funded_research_and_development_corp',
 'federal_agency',
 'us_state_government',
 'us_local_government',
 'city_local_government',
 'county_local_government',
 'inter_municipal_local_government',
 'local_government_owned',
 'municipality_local_government',
 'school_district_local_government',
 'township_local_government',
 'us_tribal_government',
 'foreign_government',
 'organizational_type',
 'corporate_entity_not_tax_exempt',
 'corporate_entity_tax_exempt',
 'partnership_or_limited_liability_partnership',
 'sole_proprietorship',
 'small_agricultural_cooperative',
 'international_organization',
 'us_government_entity',
 'community_development_corporation',
 'domestic_shelter',
 'educational_institution',
 'foundation',
 'hospital_flag',
 'manufacturer_of_goods',
 'veterinary_hospital',
 'hispanic_servicing_institution',
 'receives_contracts',
 'receives_financial_assistance',
 'receives_contracts_and_financial_assistance',
 'airport_authority',
 'council_of_governments',
 'housing_authorities_public_tribal',
 'interstate_entity',
 'planning_commission',
 'port_authority',
 'transit_authority',
 'subchapter_scorporation',
 'limited_liability_corporation',
 'foreign_owned',
 'for_profit_organization',
 'nonprofit_organization',
 'other_not_for_profit_organization',
 'the_ability_one_program',
 'private_university_or_college',
 'state_controlled_institution_of_higher_learning',
 '1862_land_grant_college',
 '1890_land_grant_college',
 '1994_land_grant_college',
 'minority_institution',
 'historically_black_college',
 'tribal_college',
 'alaskan_native_servicing_institution',
 'native_hawaiian_servicing_institution',
 'school_of_forestry',
 'veterinary_college',
 'dot_certified_disadvantage',
 'self_certified_small_disadvantaged_business',
 'small_disadvantaged_business',
 'c8a_program_participant',
 'historically_underutilized_business_zone_hubzone_firm',
 'sba_certified_8a_joint_venture',
 'highly_compensated_officer_1_name',
 'highly_compensated_officer_1_amount',
 'highly_compensated_officer_2_name',
 'highly_compensated_officer_2_amount',
 'highly_compensated_officer_3_name',
 'highly_compensated_officer_3_amount',
 'highly_compensated_officer_4_name',
 'highly_compensated_officer_4_amount',
 'highly_compensated_officer_5_name',
 'highly_compensated_officer_5_amount',
 'usaspending_permalink',
 'last_modified_date']

In [18]:
df = pd.read_csv('../usa_spending_old_data/base_awards/psc1550_fy2020.csv',low_memory=False, usecols=[
        'contract_award_unique_key',
        'parent_award_agency_name',
        'current_total_value_of_award',
        'total_obligated_amount',
        'award_base_action_date',
        'award_latest_action_date',
        'prime_award_base_transaction_description',
        'number_of_actions',
        'awarding_agency_name',
        'awarding_sub_agency_name',
        'funding_agency_name',
        'funding_sub_agency_name',
        'recipient_uei',
        'recipient_name',
        'recipient_state_code',
        'award_type'
        ])

In [19]:
column_list = ['contract_award_unique_key',
        'parent_award_agency_name',
        'current_total_value_of_award',
        'total_obligated_amount',
        'award_base_action_date',
        'award_latest_action_date',
        'prime_award_base_transaction_description',
        'number_of_actions',
        'awarding_agency_name',
        'awarding_sub_agency_name',
        'funding_agency_name',
        'funding_sub_agency_name',
        'recipient_uei',
        'recipient_name',
        'recipient_state_code',
        'award_type']

In [30]:
list = []
for year in [2020, 2021, 2022, 2023, 2024, 2025]:
    csv = pd.read_csv(f'../usa_spending_old_data/base_awards/psc1550_fy{year}.csv', low_memory=False, usecols=column_list)
    list.append(csv)

all_awards = pd.concat(list, ignore_index=True)

In [32]:
len(all_awards)

3605

In [33]:
all_awards['contract_award_unique_key'].nunique()

2109

In [37]:
by_latest = all_awards.sort_values('award_latest_action_date', ascending=True)
post_drop = by_latest.drop_duplicates('contract_award_unique_key', keep='last')
len(post_drop)

2109

In [38]:
all_awards.value_counts()

contract_award_unique_key                       parent_award_agency_name     total_obligated_amount  current_total_value_of_award  award_base_action_date  award_latest_action_date  awarding_agency_name   awarding_sub_agency_name            funding_agency_name    funding_sub_agency_name      recipient_uei  recipient_name                              recipient_state_code  award_type      prime_award_base_transaction_description                                                                                               number_of_actions
CONT_AWD_FA489020F0112_9700_FA489018D0010_9700  DEPT OF DEFENSE              2.743923e+06            2.743923e+06                  2020-09-30              2024-11-05                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  YJG1MDHLBC88   AEROVIRONMENT, INC.                         CA                    DELIVERY ORDER  COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING                                                                                           1.0                  6
CONT_AWD_FA862018F2361_9700_FA862015G4040_9700  DEPT OF DEFENSE              7.073287e+07            7.073287e+07                  2018-09-21              2026-05-18                Department of Defense  Defense Contract Management Agency  Department of Defense  Department of the Air Force  ZH4NVFG3Z526   GENERAL ATOMICS AERONAUTICAL SYSTEMS, INC.  CA                    DELIVERY ORDER  FY18 BLK 30 GCS RETROFIT                                                                                                               1.0                  6
CONT_AWD_FA862018F2372_9700_FA862015G4040_9700  DEPT OF DEFENSE              2.034309e+07            2.083821e+07                  2017-10-27              2026-03-04                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  ZH4NVFG3Z526   GENERAL ATOMICS AERONAUTICAL SYSTEMS, INC.  CA                    DELIVERY ORDER  FY18 MRC, AUTOMATIC TAKEOFF AND LANDING CONTROL                                                                                        1.0                  6
CONT_AWD_FA862019F2310_9700_FA862015G4040_9700  DEPT OF DEFENSE              1.119031e+08            1.119031e+08                  2019-03-21              2025-08-07                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  ZH4NVFG3Z526   GENERAL ATOMICS AERONAUTICAL SYSTEMS, INC.  CA                    DELIVERY ORDER  NETHERLANDS MQ-9                                                                                                                       1.0                  6
CONT_AWD_FA862020F2383_9700_FA862015G4040_9700  DEPT OF DEFENSE              4.241316e+07            4.241316e+07                  2019-10-03              2026-02-12                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  ZH4NVFG3Z526   GENERAL ATOMICS AERONAUTICAL SYSTEMS, INC.  CA                    DELIVERY ORDER  MQ-9 REAPER LINK-16 INTEGRATION                                                                                                        1.0                  6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
CONT_AWD_W911S225FA258_9700_W911S225AA090_9700  DEPT OF DEFENSE              8.380000e+04            8.380000e+04                  2025-09-29              2025-09-29                Department of Defense  Department of the Army              Department of Defense  Department of the Army       JC6XP8B7EC51   NEROS, INC.                                 CA                    BPA CALL        S2P2: UAS SOLICITATION # W911S225U1586 MASTER BLANKET PURCHASE AGREEMENT FOR BLUE LIST COMPLIANT UNMANNED AIRCRAFT SYSTEMS AND PARTS.  1.0                  1
CONT_AWD_W911S225FA259_9700_W911S225AA084_9700  DEPT OF DEFENSE              8.508500e+04            8.508500e+04                  2025-09-29              2026-02-19                Department of Defense  Department of the Army              Department of Defense  Department of the Army       UCUMUFYCXXM4   FW ACQUISITION, INC.                        CA                    BPA CALL        S2P2: UAS SOLICITATION # W911S225U1584                                                                                                 1.0                  1
CONT_AWD_FA461025F0224_9700_47QSMA19D08Q1_4732  FEDERAL ACQUISITION SERVICE  1.172600e+04            1.172600e+04                  2025-09-30              2025-09-30                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  GJMSFBCNMSK3   ATLANTIC DIVING SUPPLY, INC.                VA                    DELIVERY ORDER  SKYDIO CONTROLLERS - INV Q-496467, TOTAL $11,726.00 - (INDIRECT)                                                                       1.0                  1
CONT_AWD_FA700025F0180_9700_GS07F0426X_4732     FEDERAL ACQUISITION SERVICE  7.161824e+05            7.161824e+05                  2025-09-30              2026-05-05                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  SLPYAA7K9619   DUNCAN-PARNELL INC                          NC                    DELIVERY ORDER  SMALL UNMANNED AIRCRAFT SYSTEMS (SUAS), COMPONENTS AND TRAINING                                                                        1.0                  1
CONT_AWD_FA700025FG536_9700_47QTCA24D0081_4732  FEDERAL ACQUISITION SERVICE  1.808256e+05            1.808256e+05                  2025-09-25              2025-09-25                Department of Defense  Department of the Air Force         Department of Defense  Department of the Air Force  QQHRWD12J958   PIXAMETTIC SOLUTIONS LLC                    MO                    DELIVERY ORDER  DF 25-36 PURCHASE FOR AUTONOMOUS SYSTEMS LAB                                                                                           1.0                  1
Name: count, Length: 1287, dtype: int64

In [39]:
all_awards[all_awards['contract_award_unique_key'] == 'CONT_AWD_FA489020F0112_9700_FA489018D0010_9700' ]

,contract_award_unique_key,parent_award_agency_name,total_obligated_amount,current_total_value_of_award,award_base_action_date,award_latest_action_date,awarding_agency_name,awarding_sub_agency_name,funding_agency_name,funding_sub_agency_name,recipient_uei,recipient_name,recipient_state_code,award_type,prime_award_base_transaction_description,number_of_actions
138,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0
670,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0
1286,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0
1890,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0
2467,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0
3047,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0

In [40]:
post_drop[post_drop['contract_award_unique_key'] == 'CONT_AWD_FA489020F0112_9700_FA489018D0010_9700']

,contract_award_unique_key,parent_award_agency_name,total_obligated_amount,current_total_value_of_award,award_base_action_date,award_latest_action_date,awarding_agency_name,awarding_sub_agency_name,funding_agency_name,funding_sub_agency_name,recipient_uei,recipient_name,recipient_state_code,award_type,prime_award_base_transaction_description,number_of_actions
670,CONT_AWD_FA489020F0112_9700_FA489018D0010_9700,DEPT OF DEFENSE,2743922.75,2743922.75,2020-09-30,2024-11-05,Department of Defense,Department of the Air Force,Department of Defense,Department of the Air Force,YJG1MDHLBC88,"AEROVIRONMENT, INC.",CA,DELIVERY ORDER,"COLOMBIA RAVEN UAS, SPARE PARTS AND TRAINING",1.0

In [ ]:
connection = sql.connect('../UAS_Tracker.db')

In [47]:
post_drop.to_sql('contracts_past', connection, if_exists='replace', index=False)

2109